title: Bowen Zhang Blog
description: 风能研究 / PINN / 控制 / ROM / SOWFA

theme: null
remote_theme: cotes2020/jekyll-theme-chirpy

paginate: 10
timezone: Asia/Shanghai

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

lang: zh-CN

# 顶部导航
navbar:
  - title: 主页
    url: /
  - title: 文章
    url: /posts/
  - title: 关于我
    url: /about/
